/**
 * Rewards calculation utilities for The Graph Protocol
 *
 * Key concepts:
 * - Delegation shares represent ownership of the delegation pool
 * - Exchange rate = delegatedTokens / delegatorShares
 * - Unrealized rewards = (shares * currentExchangeRate) - originalDelegation
 */

import { weiToGRT } from './utils';

/**
 * Calculate the current exchange rate for an indexer's delegation pool
 */
export function calculateExchangeRate(
  delegatedTokens: string,
  delegatorShares: string
): number {
  const tokens = weiToGRT(delegatedTokens);
  const shares = weiToGRT(delegatorShares);

  if (shares === 0) return 1;
  return tokens / shares;
}

/**
 * Calculate unrealized rewards for a delegation position
 *
 * @param stakedTokens - Original tokens delegated (wei)
 * @param shareAmount - Shares received for delegation (wei)
 * @param indexerDelegatedTokens - Total delegated to indexer (wei)
 * @param indexerDelegatorShares - Total shares issued by indexer (wei)
 */
export function calculateUnrealizedRewards(
  stakedTokens: string,
  shareAmount: string,
  indexerDelegatedTokens: string,
  indexerDelegatorShares: string,
  indexerDelegatedThawingTokens: string = '0'
): number {
  const originalStake = weiToGRT(stakedTokens);
  const shares = weiToGRT(shareAmount);
  const exchangeRate = calculatePoolExchangeRate(
    indexerDelegatedTokens,
    indexerDelegatedThawingTokens,
    indexerDelegatorShares
  );

  // Current value of shares
  const currentValue = shares * exchangeRate;

  // Unrealized = current value - original stake
  return Math.max(currentValue - originalStake, 0);
}

/**
 * Calculate estimated APR for a delegation (simple model)
 *
 * Reward distribution in The Graph protocol:
 *   1. Indexer takes indexingRewardCut of total rewards
 *   2. Remaining (1 - cut) goes entirely to delegators — self-stake does NOT
 *      participate in the delegation pool
 *
 * @param indexerRewardsPerYear - Estimated annual rewards for indexer (GRT)
 * @param protocolCutPPM - Indexer's reward cut in PPM
 * @param totalDelegated - Total delegated to indexer (GRT)
 * @param userDelegation - User's delegation amount (GRT)
 */
export function calculateEstimatedAPR(
  indexerRewardsPerYear: number,
  protocolCutPPM: number,
  totalDelegated: number,
  userDelegation: number
): number {
  if (userDelegation === 0 || totalDelegated === 0) return 0;

  const protocolCut = protocolCutPPM / 1000000;

  // After indexer cut, entire remainder goes to delegators
  const delegationPoolRewards = indexerRewardsPerYear * (1 - protocolCut);

  // User's share of delegation pool rewards
  const userRewards = delegationPoolRewards * (userDelegation / totalDelegated);

  // APR = rewards / principal * 100
  return (userRewards / userDelegation) * 100;
}

/**
 * Full decomposition of the delegator APR estimate — "show your working".
 *
 * Every term that produces the headline APR, surfaced so a delegator can
 * reconcile the number instead of treating it as a black box (the exact
 * complaint that motivated this: a correct-but-unexplained APR jump).
 */
export interface DelegatorAPRBreakdown {
  /** Annualized indexing rewards across the whole allocation set, before cut (GRT) */
  annualIndexingRewards: number;
  /** Portion flowing to delegators after cut + over-delegation dilution (GRT) — the numerator */
  annualDelegatorRewards: number;
  /** Active earning base = delegatedTokens − delegatedThawingTokens (GRT) — the denominator */
  activeBase: number;
  /** Raw indexing-reward cut the indexer sets, 0–1 */
  rawCut: number;
  /** Effective cut applied to delegated-stake rewards, 0–1 (Horizon; differs from rawCut when over-delegated) */
  effectiveCut: number;
  /** Final APR percent, with per-allocation signal-to-stake ratios clamped to P95 (capped at 100) */
  apr: number;
  /** APR percent WITHOUT the P95 clamp — the raw projection, for transparency vs. other dashboards (capped at 100) */
  aprUncapped: number;
}

/**
 * Calculate delegator APR using per-allocation signal-weighted rewards,
 * returning the full decomposition.
 *
 * For each allocation:
 *   reward = annualIssuance × (subgraphSignal / totalNetworkSignal) × (allocation / subgraphStake)
 *
 * Reward distribution under Horizon:
 *   - Rewards generated by delegated stake are split by the *effective* cut.
 *   - Delegators receive delegatedStakeRatio × (1 − indexingRewardEffectiveCut)
 *     of total rewards. When the indexer is NOT over-delegated this is
 *     algebraically identical to (1 − rawCut); when over-delegated the
 *     delegation-ratio cap makes the effective cut diverge, and the naive
 *     (1 − rawCut) would overstate delegator APR. We therefore prefer the
 *     subgraph's effective-cut figures when supplied, falling back to
 *     (1 − rawCut) otherwise.
 *
 * @param allocations - Indexer's active allocations with subgraph signal data
 * @param protocolCutPPM - Indexer's reward cut in PPM
 * @param delegated - Active delegated base, excl. thawing (GRT) — the denominator
 * @param totalNetworkSignal - Total signal across entire network (GRT)
 * @param annualIssuance - Annual GRT issuance (GRT)
 * @param effectiveCut - Optional Horizon effective cut (0–1) from the subgraph
 * @param delegatedStakeRatio - Optional delegated-stake ratio (0–1) from the subgraph
 */
export function calculateDelegatorAPRBreakdown(
  allocations: Array<{
    allocatedTokens: string;
    subgraphDeployment: {
      signalledTokens: string;
      stakedTokens: string;
    };
  }>,
  protocolCutPPM: number,
  delegated: number,
  totalNetworkSignal: number,
  annualIssuance: number,
  effectiveCut?: number | null,
  delegatedStakeRatio?: number | null
): DelegatorAPRBreakdown {
  const rawCut = protocolCutPPM / 1000000;
  // Effective cut from the subgraph. It can legitimately be NEGATIVE — when an
  // indexer's self-stake ratio exceeds its raw cut, delegators effectively keep
  // MORE than their delegated-stake share (effCut = (rawCut − ownStakeRatio)/
  // delegatedStakeRatio). Clamping the lower bound to 0 breaks the identity
  // delegatedStakeRatio × (1 − effCut) = (1 − rawCut) and collapses APR by a
  // factor of delegatedStakeRatio (the graphops.eth bug). Only reject NaN or a
  // value above 1 (anomalous), falling back to the raw cut in that case.
  const effCutValid = effectiveCut != null && Number.isFinite(effectiveCut) && effectiveCut <= 1;
  const effCut = effCutValid ? (effectiveCut as number) : rawCut;

  const empty: DelegatorAPRBreakdown = {
    annualIndexingRewards: 0,
    annualDelegatorRewards: 0,
    activeBase: delegated,
    rawCut,
    effectiveCut: effCut,
    apr: 0,
    aprUncapped: 0,
  };

  if (delegated <= 0 || totalNetworkSignal === 0 || allocations.length === 0) return empty;

  // Compute signal-to-stake ratio for each allocation and cap outliers at P95.
  // Subgraphs with anomalously high signal relative to stake (e.g. 100x the norm)
  // generate outsized theoretical rewards that skew the APR estimate.
  const allocData = allocations.map((alloc) => {
    const allocated = weiToGRT(alloc.allocatedTokens);
    const subgraphSignal = weiToGRT(alloc.subgraphDeployment.signalledTokens);
    const subgraphStake = weiToGRT(alloc.subgraphDeployment.stakedTokens);
    const signalToStake = subgraphStake > 0 ? subgraphSignal / subgraphStake : 0;
    return { allocated, subgraphSignal, subgraphStake, signalToStake };
  }).filter((a) => a.subgraphSignal > 0 && a.subgraphStake > 0);

  if (allocData.length === 0) return empty;

  // Find P95 signal-to-stake ratio as the cap
  const ratios = allocData.map((a) => a.signalToStake).sort((a, b) => a - b);
  const p95Idx = Math.min(Math.floor(ratios.length * 0.95), ratios.length - 1);
  const signalToStakeCap = ratios[p95Idx];

  let totalRewards = 0;        // with P95 clamp
  let totalRewardsUncapped = 0; // raw, no clamp — for the transparency comparison
  for (const alloc of allocData) {
    // reward = issuance × (signal/totalSignal) × (allocated/stake)
    //        = issuance × signalToStake × allocated / totalSignal
    const cappedRatio = Math.min(alloc.signalToStake, signalToStakeCap);
    totalRewards += annualIssuance * cappedRatio * alloc.allocated / totalNetworkSignal;
    totalRewardsUncapped += annualIssuance * alloc.signalToStake * alloc.allocated / totalNetworkSignal;
  }

  // Delegator share of indexing rewards. Prefer the Horizon decomposition
  // (delegatedStakeRatio × (1 − effectiveCut)) which correctly attributes
  // nothing to delegated stake that sits above the delegation-ratio cap.
  // This is only valid with the GENUINE effective cut — the identity
  // delegatedStakeRatio × (1 − effCut) = (1 − rawCut) does NOT hold if effCut
  // has fallen back to rawCut, so in that case use (1 − rawCut) directly rather
  // than del × (1 − rawCut), which would wrongly collapse the share.
  const delegatorFraction = (effCutValid && delegatedStakeRatio != null && delegatedStakeRatio >= 0 && delegatedStakeRatio <= 1)
    ? delegatedStakeRatio * (1 - (effectiveCut as number))
    : (1 - rawCut);
  const delegatorRewards = totalRewards * delegatorFraction;
  const delegatorRewardsUncapped = totalRewardsUncapped * delegatorFraction;

  return {
    annualIndexingRewards: totalRewards,
    annualDelegatorRewards: delegatorRewards,
    activeBase: delegated,
    rawCut,
    effectiveCut: effCut,
    apr: Math.min((delegatorRewards / delegated) * 100, 100),
    aprUncapped: Math.min((delegatorRewardsUncapped / delegated) * 100, 100),
  };
}

/**
 * Calculate delegator APR (headline percent only).
 *
 * Thin wrapper over {@link calculateDelegatorAPRBreakdown} — see there for the
 * full reward-distribution model and the Horizon effective-cut handling.
 */
export function calculateDelegatorAPR(
  allocations: Array<{
    allocatedTokens: string;
    subgraphDeployment: {
      signalledTokens: string;
      stakedTokens: string;
    };
  }>,
  protocolCutPPM: number,
  delegated: number,
  totalNetworkSignal: number,
  annualIssuance: number,
  effectiveCut?: number | null,
  delegatedStakeRatio?: number | null
): number {
  return calculateDelegatorAPRBreakdown(
    allocations,
    protocolCutPPM,
    delegated,
    totalNetworkSignal,
    annualIssuance,
    effectiveCut,
    delegatedStakeRatio
  ).apr;
}

/**
 * Delegator APR after adding `addedGRT` to the active (excl. thawing) base.
 * Same model as kittiwake; the only term the browser is allowed to change is the amount.
 */
export function projectDelegatorAPR(opts: {
  allocations: Array<{
    allocatedTokens: string;
    subgraphDeployment: { signalledTokens: string; stakedTokens: string };
  }>;
  protocolCutPPM: number;
  activeBase: number;
  addedGRT?: number;
  totalNetworkSignal: number;
  annualIssuance: number;
  effectiveCut?: number | null;
  selfStakeGRT: number;
}): number {
  const delegated = opts.activeBase + (opts.addedGRT ?? 0);
  const total = opts.selfStakeGRT + delegated;
  const ratio = total > 0 ? delegated / total : null;
  return calculateDelegatorAPR(
    opts.allocations,
    opts.protocolCutPPM,
    delegated,
    opts.totalNetworkSignal,
    opts.annualIssuance,
    opts.effectiveCut,
    ratio,
  );
}

/**
 * Calculate rolling delegator APY from closed allocations.
 *
 * Uses indexingDelegatorRewards from the subgraph, which already has the
 * reward cut applied at close time (more accurate than applying the current cut).
 *
 * NOTE: This is the legacy method — it divides rewards by the *current*
 * delegation pool size, so recent delegations/undelegations distort the result.
 * Prefer calculateExchangeRateAPY when historical exchange rates are available.
 *
 * @param closedAllocations - Closed allocations with pre-calculated delegator rewards
 * @param delegatedGRT - Active GRT delegated (excl. thawing tokens)
 * @param windowDays - Rolling window (30 or 90)
 */
export function calculateRollingAPY(
  closedAllocations: Array<{ delegator_rewards_grt: number; closed_at: number }>,
  delegatedGRT: number,
  windowDays: number
): number {
  if (delegatedGRT <= 0 || closedAllocations.length === 0) return 0;

  const cutoffUnix = Math.floor(Date.now() / 1000) - windowDays * 86400;

  let delegatorRewards = 0;
  for (const alloc of closedAllocations) {
    if (alloc.closed_at >= cutoffUnix) {
      delegatorRewards += alloc.delegator_rewards_grt;
    }
  }

  if (delegatorRewards <= 0) return 0;

  return (delegatorRewards / delegatedGRT) * (365 / windowDays) * 100;
}

/**
 * Calculate the delegation pool exchange rate, excluding thawing tokens.
 *
 * rate = (delegatedTokens - delegatedThawingTokens) / delegatorShares
 *
 * Thawing tokens are excluded because they no longer generate rewards
 * but remain in delegatedTokens until withdrawn.
 */
export function calculatePoolExchangeRate(
  delegatedTokens: string,
  delegatedThawingTokens: string,
  delegatorShares: string
): number {
  const tokens = weiToGRT(delegatedTokens);
  const thawing = weiToGRT(delegatedThawingTokens);
  const shares = weiToGRT(delegatorShares);

  if (shares === 0) return 1;
  return (tokens - thawing) / shares;
}

/**
 * Calculate APY from delegation pool exchange rate changes.
 *
 * APY = ((rate_now / rate_old) ^ (365/N) - 1) × 100
 *
 * This captures everything: indexing rewards, query fees, and slashing.
 * Immune to delegation/undelegation noise because the rate is per-share.
 *
 * Credit: Marc-André (EllipfraRole / IndexerDesignPartner)
 */
export function calculateExchangeRateAPY(
  currentRate: number,
  historicalRate: number,
  windowDays: number
): number {
  if (historicalRate <= 0 || currentRate <= 0 || windowDays <= 0) return 0;

  const ratio = currentRate / historicalRate;
  if (ratio <= 1) return 0;

  return (Math.pow(ratio, 365 / windowDays) - 1) * 100;
}

/**
 * Calculate delegation capacity metrics
 */
export function calculateDelegationCapacity(
  selfStake: number,
  delegated: number,
  delegationRatio: number
): {
  maxCapacity: number;
  usedCapacity: number;
  availableCapacity: number;
  utilizationPercent: number;
} {
  const maxCapacity = selfStake * delegationRatio;
  const usedCapacity = delegated;
  const availableCapacity = Math.max(maxCapacity - delegated, 0);
  const utilizationPercent = maxCapacity > 0 ? (delegated / maxCapacity) * 100 : 100;

  return {
    maxCapacity,
    usedCapacity,
    availableCapacity,
    utilizationPercent: Math.min(utilizationPercent, 100),
  };
}

/**
 * Calculate thawing time remaining
 */
export function calculateThawingRemaining(lockedUntil: number): {
  totalSeconds: number;
  days: number;
  hours: number;
  minutes: number;
  isComplete: boolean;
  percentComplete: number;
} {
  const now = Math.floor(Date.now() / 1000);
  const remaining = Math.max(lockedUntil - now, 0);

  const days = Math.floor(remaining / 86400);
  const hours = Math.floor((remaining % 86400) / 3600);
  const minutes = Math.floor((remaining % 3600) / 60);

  // Assume 28-day thawing period for percent calculation
  const thawingPeriod = 28 * 86400;
  const elapsed = thawingPeriod - remaining;
  const percentComplete = Math.min((elapsed / thawingPeriod) * 100, 100);

  return {
    totalSeconds: remaining,
    days,
    hours,
    minutes,
    isComplete: remaining === 0,
    percentComplete: Math.max(percentComplete, 0),
  };
}

export type DelegationStatus = 'withdrawable' | 'thawing' | 'active' | 'closed';

/**
 * Derive a delegation position's display status.
 *
 * Thawing tokens take precedence over active stake (a partially-undelegated
 * position shows as thawing). Once the thaw period elapses the position is
 * "withdrawable" — surfaced as a distinct state so delegators can see at a
 * glance which positions are ready to withdraw.
 */
export function deriveDelegationStatus(
  lockedGRT: number,
  lockedUntil: number,
  isActive: boolean,
): DelegationStatus {
  if (lockedGRT > 0) {
    return calculateThawingRemaining(lockedUntil).isComplete ? 'withdrawable' : 'thawing';
  }
  return isActive ? 'active' : 'closed';
}

/**
 * Format thawing time for display
 */
export function formatThawingTime(lockedUntil: number): string {
  const { days, hours, minutes, isComplete } = calculateThawingRemaining(lockedUntil);

  if (isComplete) return 'Ready to withdraw';
  if (days > 0) return `${days}d ${hours}h remaining`;
  if (hours > 0) return `${hours}h ${minutes}m remaining`;
  return `${minutes}m remaining`;
}

/**
 * Generate CSV data for tax reporting
 */
export function generateRewardsCSV(
  delegations: Array<{
    indexerName: string;
    indexerAddress: string;
    stakedTokens: number;
    realizedRewards: number;
    unrealizedRewards: number;
    createdAt: number;
  }>,
  grtPrice: number
): string {
  const headers = [
    'Indexer Name',
    'Indexer Address',
    'Delegated (GRT)',
    'Delegated (USD)',
    'Realized Rewards (GRT)',
    'Realized Rewards (USD)',
    'Unrealized Rewards (GRT)',
    'Unrealized Rewards (USD)',
    'Delegation Date',
  ];

  const rows = delegations.map((d) => [
    d.indexerName,
    d.indexerAddress,
    d.stakedTokens.toFixed(2),
    (d.stakedTokens * grtPrice).toFixed(2),
    d.realizedRewards.toFixed(2),
    (d.realizedRewards * grtPrice).toFixed(2),
    d.unrealizedRewards.toFixed(2),
    (d.unrealizedRewards * grtPrice).toFixed(2),
    new Date(d.createdAt * 1000).toISOString().split('T')[0],
  ]);

  const totalStaked = delegations.reduce((sum, d) => sum + d.stakedTokens, 0);
  const totalRealized = delegations.reduce((sum, d) => sum + d.realizedRewards, 0);
  const totalUnrealized = delegations.reduce((sum, d) => sum + d.unrealizedRewards, 0);

  rows.push([
    'TOTAL',
    '',
    totalStaked.toFixed(2),
    (totalStaked * grtPrice).toFixed(2),
    totalRealized.toFixed(2),
    (totalRealized * grtPrice).toFixed(2),
    totalUnrealized.toFixed(2),
    (totalUnrealized * grtPrice).toFixed(2),
    '',
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
}
