-- Moved.
--
-- The database schema now lives in `nightswatchhq/kittiwake` at `db/schema.sql`, and a new column
-- is added there and nowhere else. kittiwake#31.
--
--   https://github.com/nightswatchhq/kittiwake/blob/main/db/schema.sql
--
-- WHY
--
-- These tables are read on nearly every route of that service and, since the crons were ported,
-- written by it and no other. This repository is to hold no server code at all (kittiwake#29), and
-- a repo that does not write to a database has no business owning its schema.
--
-- It was never only tidiness. A live 200-with-an-empty-array (kittiwake#24) was diagnosed by
-- reading the authoritative column types out of *this* file from *that* repository, and doing so
-- turned up four wrongly-typed columns where the issue had recorded two. None of them was visible
-- from inside the code that was wrong. kittiwake#2 then made those queries check themselves against
-- the schema when they compile, which only works if the schema is somewhere the compiler can see.
--
-- WHAT IS STILL HERE
--
-- `migrate-studio*.sql`. The Dock has not ported yet (kittiwake#16) and those tables are still
-- this repository's. They go across with it. The one exception already copied over is
-- `sync_bounties`, because `reconcile-bounties` writes it from there (kittiwake#30) and a statement
-- checked at compile time needs the table to exist; that duplication is marked as temporary at both
-- ends.
--
-- This file is kept rather than deleted so that anyone who goes looking for it finds the redirect
-- instead of concluding the schema was never written down.
